@startuml

package "Frameworks & Drivers" {
    database "PostgreSQL" as db
    [Main]
    [Cognito API]
    [External Web Site] as "External Web Site"
    [Bedrock API] 
}

package "Interface Adapters" {
    [PostgresRepository]
    [Controller]
    [AuthMiddleware] ..> [Cognito API]
    [RecipeScraper]..> [External Web Site]
    [LLM Client Impl] ..> [Bedrock API]
}

package "Use Case" {
    [UseCase] .> [Repository]
    [Repository] <<interface>>
    [LLMClient] <<interface>>
    [Scraper] <<interface>>
    [UseCase] .> [LLMClient]
    [UseCase] .> [Scraper]
}

db <.. [PostgresRepository]
[Main] --> [Controller] 
[Main] --> [PostgresRepository]
[Main] --> [AuthMiddleware]
[Controller] ..> [UseCase]
[RecipeScraper] ..|> [Scraper] : implements
[PostgresRepository] ..|> [Repository] : implements
[LLM Client Impl] ..|> [LLMClient] : implements
[UseCase] ..> [Entity]
[Entity]

@enduml